version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=production # Adjust if needed

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - redis
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
